/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Basics;
import java.util.Random;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }


   public static String  pluralize (String animal , int num) {
        if (num > 1 || num == 0){
            return animal+"s";
        }else{
            return animal;
        }
    }


//    Write a function called flipNHeads that accepts an integer n and flips coins until n heads are flipped in a row. Simulate coin flipping by choosing a random number between 0 and 1. Numbers below .5 are considered tails. Numbers at and above .5 are considered heads. Print out heads or tails on one line for each flip. Print It took FLIPS flips to flip N heads in a row. once n heads have been in a row.
    public static void flipNHeads(int n) {
        int flips = 0;
        int headsNumber = 0;
        while (headsNumber != n){
            flips++;
            Random random = new Random();
            double randomNumber = random.nextDouble();
            if (randomNumber  >= 0.5){
                System.out.println("heads");
                headsNumber = headsNumber + 1;
            }else {
                System.out.println("tails ");
                headsNumber = 0;

            }

        }
        System.out.println("It took " + flips + " flips to flip " + headsNumber + " heads in a row .");
    }


    public static void clock(){
        while (true){

            LocalDateTime now = LocalDateTime.now();
            int hour = now.getHour();
            int minute = now.getMinute();
            int second = now.getSecond();
// or, if you're feeling fancy
            String time = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));

            while (second== LocalDateTime.now().getSecond()){

                continue;
            }
            System.out.println(time);
        }

    }

    public static void main (String[]args){
         int dogCount = 1;
                System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

                int catCount = 2;
                System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

                int turtleCount = 0;
                System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");


                flipNHeads(1);
                 clock();


            }

    }