/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

        System.out.println("dice roll " + roll(5));
        int[] array = {1,2,3,4,6,1,8};
        System.out.println( containsDuplicates(array));


    }



    //Rolling Dice
    public static ArrayList roll(int n){
        ArrayList<Integer> resultArray = new ArrayList<Integer>();
        int min = 1;
        int max = 6;
        for (int i = 0; i < n; i++) {
            int random = (int) (Math.random()* (max - min)) + 1;
            resultArray.add(random);
        }
        return resultArray;
    }
    //Contains Duplicates

    public static boolean containsDuplicates(int[] duplicateArr) {

        for (int i = 0; i < duplicateArr.length; i++) {
            for (int j = 0; j < duplicateArr.length; j++) {
                if (i != j) {
                    if (duplicateArr[i] == duplicateArr[j]) {

                        return true;
                    }
                }
            }
        }

        return false;
    }

    // Calculating Averages


}


