/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main (String arg[]){
        System.out.print("hello\n");

        Restaurant newRestaurant = new Restaurant("Fire fly",4);
        newRestaurant.addReview("haneen" , 3);
        newRestaurant.addReview("zaina" , 2);
        newRestaurant.addReview("bilal" , 5);

        System.out.println(newRestaurant);

       Shop newShop = new Shop("almohet","see food",3);
        newShop.addReview("zaina" , 2);
    }
}
