/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testingRestaurantClass() {

        //  Test restaurant before review
        Restaurant testRestaurant = new Restaurant("firefly", 5);
        assertEquals("firefly", testRestaurant.getName());
        assertEquals(5, testRestaurant.getPrice());
       assertEquals("Restaurant Name:firefly,stars:0.0, Price Category:5.0$, reviews=[]" , testRestaurant.toString());


        //Test review
        Review testReview = new Review("ahmad", 4);
        assertEquals("ahmad rate :4.0 stars ", testReview.toString());

        //  Test addReview method
        testRestaurant.addReview("haneen", 3);
        assertEquals("Restaurant Name:firefly,stars:3.0, Price Category:5.0$, reviews=[haneen rate :3.0 stars ]" , testRestaurant.toString());

    }}
